# Part B
# To create an image dataset to be used by AI team build an image classifier data. Profile images of people are given

1. Read/import images from folder ‘training_images’.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
import os, zipfile

In [3]:
from zipfile import ZipFile

# specifying the zip file name
file_name = "C:\\Users\\vrooky-montzo\\Downloads\\training_images-20211126T092819Z-001.zip"
  
# opening the zip file in READ mode
with ZipFile(file_name, 'r') as zip:
    # printing all the contents of the zip file
    zip.printdir()
  
    # extracting all the files
    print('Extracting all the files now...')
    zip.extractall()
    print('Done!')

File Name                                             Modified             Size
training_images/real_00947.jpg                 2019-10-16 04:27:36       165936
training_images/real_01052.jpg                 2019-10-16 04:27:36        99194
training_images/real_01042.jpg                 2019-10-16 04:27:36       132379
training_images/real_00964.jpg                 2019-10-16 04:27:36       137657
training_images/real_01053.jpg                 2019-10-16 04:27:36        88502
training_images/real_00971.jpg                 2019-10-16 04:27:36        68693
training_images/real_01057.jpg                 2019-10-16 04:27:36       163006
training_images/real_01044.jpg                 2019-10-16 04:27:36       111944
training_images/real_01041.jpg                 2019-10-16 04:27:36       158596
training_images/real_01067.jpg                 2019-10-16 04:27:36       116880
training_images/real_00969.jpg                 2019-10-16 04:27:36       111096
training_images/real_00956.jpg          

In [4]:
cd

C:\Users\vrooky-montzo


In [5]:
import pathlib
data_dir = pathlib.Path("C:\\Users\\vrooky-montzo\\Downloads\\training_images")
data_dir

WindowsPath('C:/Users/vrooky-montzo/Downloads/training_images')

In [6]:
import os,cv2
from PIL import Image
for i in os.listdir(data_dir):

    cascPath = "haarcascade_frontalface_default.xml"
    faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + cascPath)
    
    img = cv2.imread('training_images/'+i)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, 1.01)
    print (i)
    print(len(faces))
    
    print(faces)
   

real_00001.jpg
1
[[153 143 422 422]]
real_00002.jpg
1
[[ 81 141 436 436]]
real_00003.jpg
4
[[467 344  36  36]
 [416 535  59  59]
 [261  10 125 125]
 [ 33 118 367 367]]
real_00004.jpg
3
[[130 168 364 364]
 [ 14  11 161 161]
 [271 210 317 317]]
real_00005.jpg
5
[[421 285  69  69]
 [226  23  90  90]
 [326  60 134 134]
 [ 57 199 337 337]
 [422 234  53  53]]
real_00006.jpg
1
[[ 65  60 472 472]]
real_00007.jpg
7
[[ 17 388  27  27]
 [361 475 112 112]
 [ 74 249 127 127]
 [223 214  81  81]
 [341 387  87  87]
 [247 500  29  29]
 [220 126 336 336]]
real_00008.jpg
7
[[151 388  49  49]
 [282  25  63  63]
 [326 431  86  86]
 [254 214 245 245]
 [458  83  71  71]
 [ 14 144 380 380]
 [301  65  74  74]]
real_00009.jpg
4
[[308   7  35  35]
 [ 20 529  37  37]
 [ 36 517  43  43]
 [233  53 362 362]]
real_00010.jpg
1
[[ 19  87 442 442]]
real_00011.jpg
1
[[ 89 134 430 430]]
real_00012.jpg
4
[[261  24  52  52]
 [422  85  30  30]
 [113 187 381 381]
 [143  35  97  97]]
real_00013.jpg
2
[[282  37  50  50]
 [ 79 1

In [7]:
from PIL import Image
import pandas as pd
# open the image
metaList=[]
cascPath = "haarcascade_frontalface_default.xml"
faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + cascPath)
for i in os.listdir(data_dir):
    image = Image.open('training_images/'+i)
    img = cv2.imread('training_images/'+i)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, 1.01)
    info_dict = {
        "Image name": image.filename,
        "Image Size": image.size,
        "Image Height": image.height,
        "Toatl_Faces":len(faces),
        "Image Width": image.width,
    }
    metaList.append(info_dict)

df = pd.DataFrame(metaList)
df

Image name  Image Size  Image Height  Toatl_Faces  \
0     training_images/real_00001.jpg  (600, 600)           600            1   
1     training_images/real_00002.jpg  (600, 600)           600            1   
2     training_images/real_00003.jpg  (600, 600)           600            4   
3     training_images/real_00004.jpg  (600, 600)           600            3   
4     training_images/real_00005.jpg  (600, 600)           600            5   
...                              ...         ...           ...          ...   
1086  training_images/real_01077.jpg  (600, 600)           600            1   
1087  training_images/real_01078.jpg  (600, 600)           600            1   
1088  training_images/real_01079.jpg  (600, 600)           600            1   
1089  training_images/real_01080.jpg  (600, 600)           600            1   
1090  training_images/real_01081.jpg  (600, 600)           600            4   

      Image Width  
0             600  
1             600  
2             600  
3             600  
4             600  
...           ...  
1086          600  
1087          600  
1088          600  
1089          600  
1090          600  

[1091 rows x 5 columns]

In [8]:
# saving the dataframe
df.to_csv('pd.csv')